name = "demo-landing"
compatibility_date = "2025-05-03"
main = ".next/static"

[site]
bucket = ".next/out"

[build]
command = "next build && next export"
output_directory = ".next/out"

[env.production]
workers_dev = true 