# Конфигурация Cloudflare Workers для проекта на Next.js 15

name = "landing"
compatibility_date = "2025-05-03"
compatibility_flags = ["nodejs_compat", "unsafe_eval"]
main = ".open-next/worker.js"

# Настройки Workers для оптимальной работы с Next.js
workers_dev = true

# Доступ к ассетам
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Настройки окружения для Next.js
[vars]
NEXT_SKIP_CSP = "1"
NEXT_DISABLE_COMPRESSION = "1"
NEXT_BYPASS_ALIAS_CHECK = "1"

[build]
command = "NEXT_BYPASS_ALIAS_CHECK=1 pnpm run build"

# Логи для диагностики
[observability.logs]
enabled = true

# Разрешаем выполнение динамического JavaScript (необходимо для MDX)
[env.production]
ENABLE_UNSAFE_EVAL = true

[env.preview]
ENABLE_UNSAFE_EVAL = true
