name = "landing"
compatibility_date = "2025-05-03"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS" 

[observability.logs]
enabled = true