# Конфигурация Cloudflare Pages для проекта на Next.js 15

name = "landing"
compatibility_flags = ["nodejs_compat", "NO_RESPONSE_COMPRESSION"]

# Указываем директорию для Pages деплоя - это критично для Cloudflare Pages
pages_build_output_dir = ".vercel/output/static"

# Добавляем переменные окружения для обхода ограничений CSP
[vars]
NEXT_SKIP_CSP = "1"
NEXT_DISABLE_COMPRESSION = "1" 